# PITCHER
FROM ghcr.io/codesandbox/devcontainers/universal:latest


# PINT
#FROM node:22-bookworm

#RUN apt-get update && apt-get install -y git zsh curl && rm -rf /var/lib/apt/lists/*

#RUN corepack enable
 
#WORKDIR /workspace/project