// This file is auto-generated by @hey-api/openapi-ts

export type SuccessResponse = {
  /**
   * Status code for successful operations
   */
  status: 0;
  /**
   * Result payload for the operation
   */
  result: {
    [key: string]: unknown;
  };
};

export type ErrorResponse = {
  /**
   * Status code for error operations
   */
  status: 1;
  /**
   * Error details
   */
  error: {
    [key: string]: unknown;
  };
};

export type ProtocolError = {
  /**
   * Error code
   */
  code: number;
  /**
   * Error message
   */
  message: string;
  /**
   * Additional error data
   */
  data?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Status of a setup shell step
 */
export type SetupShellStatus = "SUCCEEDED" | "FAILED" | "SKIPPED";

export type Step = {
  /**
   * Name of the setup step
   */
  name: string;
  /**
   * Command to execute for this step
   */
  command: string;
  /**
   * ID of the shell executing the command
   */
  shellId: string | null;
  finishStatus: SetupShellStatus;
};

export type SetupProgress = {
  /**
   * Current state of the setup process
   */
  state: "IDLE" | "IN_PROGRESS" | "FINISHED" | "STOPPED";
  /**
   * List of setup steps
   */
  steps: Array<Step>;
  /**
   * Index of the current step being executed
   */
  currentStepIndex: number;
};

export type SetupGetData = {
  body: {
    [key: string]: unknown;
  };
  path?: never;
  query?: never;
  url: "/setup/get";
};

export type SetupGetErrors = {
  /**
   * Error retrieving setup progress
   */
  400: ErrorResponse & {
    error?: ProtocolError;
  };
};

export type SetupGetError = SetupGetErrors[keyof SetupGetErrors];

export type SetupGetResponses = {
  /**
   * Successful operation
   */
  200: SuccessResponse & {
    result?: SetupProgress;
  };
};

export type SetupGetResponse = SetupGetResponses[keyof SetupGetResponses];

export type SetupSkipStepData = {
  body: {
    /**
     * Index of the step to skip
     */
    stepIndexToSkip: number;
  };
  path?: never;
  query?: never;
  url: "/setup/skip";
};

export type SetupSkipStepErrors = {
  /**
   * Error skipping step
   */
  400: ErrorResponse & {
    error?: ProtocolError;
  };
};

export type SetupSkipStepError = SetupSkipStepErrors[keyof SetupSkipStepErrors];

export type SetupSkipStepResponses = {
  /**
   * Successful operation
   */
  200: SuccessResponse & {
    result?: SetupProgress;
  };
};

export type SetupSkipStepResponse =
  SetupSkipStepResponses[keyof SetupSkipStepResponses];

export type SetupSkipAllData = {
  body: unknown;
  path?: never;
  query?: never;
  url: "/setup/skipAll";
};

export type SetupSkipAllErrors = {
  /**
   * Error skipping all steps
   */
  400: ErrorResponse & {
    error?: ProtocolError;
  };
};

export type SetupSkipAllError = SetupSkipAllErrors[keyof SetupSkipAllErrors];

export type SetupSkipAllResponses = {
  /**
   * Successful operation
   */
  200: SuccessResponse & {
    result?: SetupProgress;
  };
};

export type SetupSkipAllResponse =
  SetupSkipAllResponses[keyof SetupSkipAllResponses];

export type SetupDisableData = {
  body: unknown;
  path?: never;
  query?: never;
  url: "/setup/disable";
};

export type SetupDisableErrors = {
  /**
   * Error disabling setup
   */
  400: ErrorResponse & {
    error?: ProtocolError;
  };
};

export type SetupDisableError = SetupDisableErrors[keyof SetupDisableErrors];

export type SetupDisableResponses = {
  /**
   * Successful operation
   */
  200: SuccessResponse & {
    result?: SetupProgress;
  };
};

export type SetupDisableResponse =
  SetupDisableResponses[keyof SetupDisableResponses];

export type SetupEnableData = {
  body: unknown;
  path?: never;
  query?: never;
  url: "/setup/enable";
};

export type SetupEnableErrors = {
  /**
   * Error enabling setup
   */
  400: ErrorResponse & {
    error?: ProtocolError;
  };
};

export type SetupEnableError = SetupEnableErrors[keyof SetupEnableErrors];

export type SetupEnableResponses = {
  /**
   * Successful operation
   */
  200: SuccessResponse & {
    result?: SetupProgress;
  };
};

export type SetupEnableResponse =
  SetupEnableResponses[keyof SetupEnableResponses];

export type SetupInitData = {
  body: unknown;
  path?: never;
  query?: never;
  url: "/setup/init";
};

export type SetupInitErrors = {
  /**
   * Error initializing setup
   */
  400: ErrorResponse & {
    error?: ProtocolError;
  };
};

export type SetupInitError = SetupInitErrors[keyof SetupInitErrors];

export type SetupInitResponses = {
  /**
   * Successful operation
   */
  200: SuccessResponse & {
    result?: SetupProgress;
  };
};

export type SetupInitResponse = SetupInitResponses[keyof SetupInitResponses];

export type SetupSetStepData = {
  body: {
    /**
     * Index of the step to set as current
     */
    stepIndex: number;
  };
  path?: never;
  query?: never;
  url: "/setup/setStep";
};

export type SetupSetStepErrors = {
  /**
   * Error setting current step
   */
  400: ErrorResponse & {
    error?: ProtocolError;
  };
};

export type SetupSetStepError = SetupSetStepErrors[keyof SetupSetStepErrors];

export type SetupSetStepResponses = {
  /**
   * Successful operation
   */
  200: SuccessResponse & {
    result?: SetupProgress;
  };
};

export type SetupSetStepResponse =
  SetupSetStepResponses[keyof SetupSetStepResponses];
