export enum PitcherErrorCode {
  // CORE
  CRITICAL_ERROR = 0,
  FEATURE_UNAVAILABLE = 1,
  NO_ACCESS = 2,
  RATE_LIMIT = 3,

  // FS
  INVALID_ID = 100,
  INVALID_PATH = 101,
  RAWFS_ERROR = 102,

  // SHELL
  SHELL_NOT_ACCESSIBLE = 200,
  SHELL_CLOSED = 201,
  SHELL_NOT_FOUND = 204,

  // MODELS
  MODEL_NOT_FOUND = 300,

  // GIT
  GIT_OPERATION_IN_PROGRESS = 400,
  GIT_REMOTE_FILE_NOT_FOUND = 404,
  GIT_FETCH_FAIL = 410,
  GIT_PULL_CONFLICT = 420,
  GIT_RESET_LOCAL_REMOTE_ERROR = 430,
  GIT_PUSH_FAIL = 440,
  GIT_RESET_CHECKOUT_INITIAL_BRANCH_FAIL = 450,
  GIT_PULL_FAIL = 460,
  GIT_TRANSPOSE_LINES_FAIL = 470,

  // CHANNEL
  CHANNEL_NOT_FOUND = 500,

  // TASKS
  CONFIG_FILE_ALREADY_EXISTS = 600,
  TASK_NOT_FOUND = 601,
  COMMAND_ALREADY_CONFIGURED = 602,

  // COMMANDS
  COMMAND_NOT_FOUND = 704,

  // AI
  AI_NOT_AVAILABLE = 800,
  PROMPT_TOO_BIG = 801,
  FAILED_TO_RESPOND = 802,
  AI_TOO_FREQUENT_REQUESTS = 803,
  AI_CHAT_NOT_FOUND = 814,

  // BOX
  BOX_NOT_AVAILABLE = 900,
}
