// This file is auto-generated by @hey-api/openapi-ts

export type SuccessResponse = {
    /**
     * Status code for successful operations
     */
    status: 0;
    /**
     * Result payload for the operation
     */
    result: {
        [key: string]: unknown;
    };
};

export type ErrorResponse = {
    /**
     * Status code for error operations
     */
    status: 1;
    error: ({
        code?: 'DefaultError';
    } & DefaultError) | ({
        code?: 'RawFsError';
    } & RawFsError);
};

export type DefaultError = {
    code: PitcherErrorCode;
    /**
     * Additional error details
     */
    data?: {
        [key: string]: unknown;
    } | null;
    /**
     * Human-readable error message that can be displayed to users
     */
    publicMessage?: string | null;
};

export type RawFsError = {
    /**
     * RAWFS_ERROR code
     */
    code: 102;
    data: {
        /**
         * File system error number, or null if not available
         */
        errno: unknown;
    };
    /**
     * Human-readable error message that can be displayed to users
     */
    publicMessage?: string | null;
};

/**
 * Enumeration of error codes
 */
export type PitcherErrorCode = 0 | 1 | 2 | 3 | 100 | 101 | 102 | 200 | 201 | 204 | 300 | 400 | 404 | 410 | 420 | 430 | 440 | 450 | 460 | 470 | 500 | 600 | 601 | 602 | 704 | 800 | 801 | 802 | 803 | 814;

export type WriteFileRequest = {
    /**
     * File path to write to
     */
    path: string;
    /**
     * File content as binary data (Uint8Array)
     */
    content: Blob | File;
    /**
     * Whether to create the file if it doesn't exist
     */
    create?: boolean;
    /**
     * Whether to overwrite the file if it exists
     */
    overwrite?: boolean;
};

export type WriteFileData = {
    body: WriteFileRequest;
    path?: never;
    query?: never;
    url: '/fs/writefile';
};

export type WriteFileErrors = {
    /**
     * Error writing file
     */
    400: ErrorResponse & {
        error?: ({
            code?: 'DefaultError';
        } & DefaultError) | ({
            code?: 'RawFsError';
        } & RawFsError);
    };
};

export type WriteFileError = WriteFileErrors[keyof WriteFileErrors];

export type WriteFileResponses = {
    /**
     * Successful operation
     */
    200: SuccessResponse & {
        result?: {
            [key: string]: unknown;
        };
    };
};

export type WriteFileResponse = WriteFileResponses[keyof WriteFileResponses];